[project]
authors = ["Emily Herbert"]
entry = "main.sw"
license = "Apache-2.0"
name = "counter_contract"

[dependencies]
counter_library = { path = "../counter_library" }
std = { git = "http://github.com/FuelLabs/sway" }

