[project]
author = "Emily Herbert"
entry = "main.sw"
license = "Apache-2.0"
name = "test_counter"

[dependencies]
std = { git = "http://github.com/FuelLabs/sway-lib-std", version = "v0.0.1" }
core = { git = "http://github.com/FuelLabs/sway-lib-core", version = "v0.0.1" }