[project]
authors = ["Emily Herbert"]
entry = "main.sw"
license = "Apache-2.0"
name = "counter_example"

[dependencies]
#std = { git = "http://github.com/FuelLabs/sway" }
#core = { git = "http://github.com/FuelLabs/sway" }

